"use client";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthModalWrapper from "@/components/AuthModalWrapper";
import Header from "@/components/Header";
import { ThemeProvider } from "@/components/ThemeProvider";
import { Inter } from "next/font/google";
//import { AuthProvider } from "@/hooks/useAuth";
import { AuthProvider } from '@/lib/auth-context';
import { Toaster } from "react-hot-toast";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const inter = Inter({ subsets: ["latin"] });

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const metadata: Metadata = {
  title: 'Phapsite',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.className} antialiased`}
      >
        <AuthProvider>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <Header />
            <div className="pt-5">
              <AuthModalWrapper>
                <main>{children}</main>
                <Toaster
                  position="top-right"
                  toastOptions={{
                    duration: 4000,
                    style: {
                      background: "#363636",
                      color: "#fff",
                    },
                  }}
                />
              </AuthModalWrapper>
            </div>
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}






